#pragma once

// Text components for the ECS pipeline.
//   Text        – authoring data (string, font, size, colour, alignment...).
//   TextLayout  – generated by text_layout_system: the per-glyph quads (atlas
//                 texture + normalised uv rect + colour + local matrix) plus the
//                 laid-out block size. Consumed by the generic batch collector.

#include <string>
#include <vector>
#include <cstdint>

#include <glm/glm.hpp>
#include <texture.hpp>

#include "FontAsset.hpp"
#include "../assets/Handle.hpp"

namespace gld::ecs {

    enum class TextAlign : int { Left = 0, Center, Right };

    struct Text {
        std::u32string text;
        Handle<FontAsset> font;
        int size = 48;                       // pixel size
        glm::vec4 color{ 1.f };
        TextAlign align = TextAlign::Left;
        float leading = 0.f;                 // extra px between lines
        float max_width = 0.f;               // 0 = no wrapping (px)
        glm::vec2 anchor{ 0.5f, 0.5f };      // block anchor: (0,0)=top-left .. (1,1)=bottom-right
        uint64_t rev = 1;                    // bump to force a re-layout
    };

    // One laid-out glyph: a textured quad in the entity's local (pixel) space.
    struct GlyphQuad {
        std::shared_ptr<Texture<TexType::D2>> atlas;
        glm::vec4 uv{ 0.f };    // normalised atlas rect (x, y, w, h)
        glm::vec4 color{ 1.f };
        glm::mat4 local{ 1.f }; // translate(center) * scale(w, h) about the entity origin
    };

    struct TextLayout {
        std::vector<GlyphQuad> quads;
        glm::vec2 size{ 0.f };  // laid-out block size in pixels
        uint64_t src_rev = 0;   // Text.rev this layout was built from
    };
}
